---
# Tasks for common role
- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install common packages (RHEL/CentOS)
  yum:
    name: "{{ common_packages_rhel }}"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Set timezone
  timezone:
    name: "{{ system_timezone }}"
